### ISSUE TITLE
[Issue] Geometries in "blocks" folder on bedrock fail to load textures when referenced by non-block resources

### ISSUE THREAD

**Issue by Kas-tle** [JannisX11/blockbench#1501]
### Description

When trying to open a geometry in the blocks folder of a bedrock resource pack, resolution of textures applied by attachables and entities fail.

### Reproduction
- Unzip the attached pack
- Attempt to open any model, such as `assets/models/blocks/gmdl_14`
- Observe that no textures load for the model, despite the texture `textures/geyser/geyser_custom/1` being referenced in attchable `attachables/geyser_custom/gmdl_14.attachable.json`
- Observe the following error in console: 
```
bedrock.js:408 Error: ENOENT: no such file or directory, open 'C:\manifest.json'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
    at Object.readFileSync (node:fs:453:35)
    at e.readFileSync (node:electron/js2c/asar_bundle:5:9160)
    at BedrockBlockManager.getBlockFile (bedrock.js:352:46)
    at BedrockBlockManager.initBlock (bedrock.js:406:29)
    at parseGeometry (bedrock.js:729:66)
    at Codec.parse (bedrock.js:1050:4)
    at Codec.load (bedrock.js:922:8)
    at loadIfCompatible (io.js:69:12)
```
- Rename `models/blocks` to an arbitrary name, such as `models/geyser`
- Close and reopen the model
- Observe that the texture is now automatically loaded correctly
- Observe that there are no errors in console

### Model Format
Appears to be related to the fact that anything loaded in the blocks folder is automatically loaded as a Bedrock Block, though these geometries can also be used by entities and attachables.

### Blockbench Version
4.3.1, Desktop

### OS
Windows 11

**Comment by Kas-tle** [comment]
Just realized I forgot the attachment... will upload when I have access to my computer. Apologies xD

**Comment by Kas-tle** [comment]
Here you go
[geyser_resources_cc.zip](https://github.com/JannisX11/blockbench/files/9275712/geyser_resources_cc.zip)

**Comment by JannisX11** [comment]
That is definitely intended, but I see why you would like it to load from attachables and entities as well.

**Comment by Kas-tle** [comment]
I guess perhaps some sort of global setting that is off by default and overrides the format? I can see why just adding a prompt would waste people's time in the majority of cases.

**Comment by JannisX11** [comment]
How about opening the entity or attachable file automatically opens the model as an entity?

**Comment by Kas-tle** [comment]
That would be cool and would actually solve other issues (e.g. less texture picking when a geometry is reused by multiple entity definitions).
