### ISSUE TITLE
Issue Summary

### ISSUE THREAD

**Issue by JulyyBr** [JannisX11/blockbench#2208]
### What are you trying to do, and what do you expect to happen?

export model

### What happens instead?

Error while exporting:
TypeError: Failed to fetch
    at elemental2.dom.DomGlobal.fetch(DomGlobal.java:1799) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1708809336756:1751:484)
    at com.tom.cpm.blockbench.convert.BlockbenchExport.doExport(BlockbenchExport.java:126) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1708809336756:1733:209)
    at com.tom.cpm.blockbench.convert.ProjectConvert.prepExport$lambda$lambda(ProjectConvert.java:64) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1708809336756:1975:42)
    at com.tom.cpm.blockbench.convert.ProjectConvert.prepExport$lambda(ProjectConvert.java:61) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1708809336756:2001:41)
    at com.tom.cpm.web.client.render.RenderSystem.withContext(RenderSystem.java:1229) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1708809336756:6534:67)
    at com.tom.cpm.blockbench.convert.ProjectConvert.prepExport$lambda(ProjectConvert.java:61) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1708809336756:1974:23)
    at com.tom.cpm.blockbench.convert.ProjectConvert.prepExport(ProjectConvert.java:60) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1708809336756:2000:55)
    at com.google.gwt.dev.jjs.intrinsic.com.google.gwt.lang.Runtime(Runtime.java:165) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1708809336756:17:47)
    at new Promise (<anonymous>)
    at com.tom.cpm.blockbench.convert.ProjectConvert.prepExport(ProjectConvert.java:60) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1708809336756:1999:48)
    at com.tom.cpm.blockbench.util.PopupDialogs.runTaskWithWarning(PopupDialogs.java:144) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1708809336756:2157:32)
    at com.tom.cpm.blockbench.convert.ProjectConvert.exportWithWarnings(ProjectConvert.java:56) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1708809336756:1967:212)
    at com.tom.cpm.blockbench.format.CPMCodec.init(CPMCodec.java:54) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1708809336756:2037:52)
    at com.google.gwt.dev.jjs.intrinsic.com.google.gwt.lang.Runtime(Runtime.java:165) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1708809336756:17:47)
    at com.tom.cpm.blockbench.BBActions.load$lambda(BBActions.java:97) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1708809336756:1631:63)
    at com.google.gwt.dev.jjs.intrinsic.com.google.gwt.lang.Runtime(Runtime.java:165) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1708809336756:17:47)
    at Action.click (file:///C:/Users/annaj/AppData/Local/Programs/Blockbench/resources/app.asar/js/interface/actions.js:266:10)
    at Action.trigger (file:///C:/Users/annaj/AppData/Local/Programs/Blockbench/resources/app.asar/js/interface/actions.js:332:10)
    at HTMLLIElement.<anonymous> (file:///C:/Users/annaj/AppData/Local/Programs/Blockbench/resources/app.asar/js/interface/actions.js:291:10)

### Model format in which the issue occurs

cpmproject

### Blockbench variant

Website, PWA, Program

### Blockbench version

last

### Operating System

WIndows 10

### Installed Blockbench plugins

cpm_plugin

**Comment by JannisX11** [comment]
This is not an issue with Blockbench but with the plugin that you are using. Please report this to the author of the plugin instead.
